# Generated by Django 3.0 on 2019-12-16 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacationplanner', '0003_auto_20191215_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='vacation',
            name='itinerary',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='vacations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacations', to='vacationplanner.Vacation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
