# Generated by Django 3.0 on 2019-12-16 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacationplanner', '0004_auto_20191216_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='vacations',
            new_name='vacation',
        ),
        migrations.AlterField(
            model_name='vacation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
