# Generated by Django 3.0 on 2019-12-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacationplanner', '0005_auto_20191216_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='vacation',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
